### ISSUE TITLE
Enforce UTF-8 BOM to Prevent Issues with PB IDE

### ISSUE THREAD

**Issue by tajmone** [peterthomashorn/purebasic-language-for-sublime-text#34]
Currently this package will use UTF-8 as the default encoding for PB sources, but that doesn't play well with the standard way sources are handled by the native PB IDE, which uses UTF-8 BOM to distinguish between Unicode and ASCII sources, for historical reasons.

In my previous package I had enforced UTF-8 BOM as the default encoding, for in this case it makes sense, since that's the idiomatic way of the language. Unless we enforce the BOM, we'll be facing encoding conflicts when other users edit files using the PB IDE — without a BOM, the sources will be treated as ASCII file, which will lead to unexpected single-char encoding (according to the OS native settings) and sources corruption for any chars above value 127.

There's nothing wrong with using UTF-8 with a BOM, and it's quite common in the Windows world for the same historical reasons as with PB, i.e. apps switching from single-char encodings to Unicode.

If it's OK with you, I'll create a PR with the UTF-8 BOM settings file (which I still have a copy locally) and also tweak all the test files to add the BOM.

**Comment by peterthomashorn** [comment]
> If it's OK with you, I'll create a PR with the UTF-8 BOM settings file (which I still have a copy locally) and also tweak all the test files to add the BOM.

It is. Reading about this, some bell is ringing in my memory. I think I learned about BOM the first time with PureBasic _years_ ago.

**Comment by tajmone** [comment]
OK, I've added the BOM setting in PR #38.

I didn't add a BOM to the PB test files since I've already done that in PR #35, where I add EditorConfig settings for code consistency rules and tweak all files that didn't meet the rules.

I've tested the new settings: now when you create a new file and set its syntax to "PureBasic" its encoding is set as "UTF-8 with BOM" — under Windows, the encoding shown in ST4's status bar is not automatically refreshed, you need to change tab and go back to see the BOM mentioned, but internally the encoding has immediate effect (must be a UI refresh bug).

Of course, this new setting is only enforced on new PB files, or pre-existing files for which the automatic encoding-detection algorithm doesn't detect a specific encoding (or is unable to). I'm not entirely sure that it will add a BOM to pre-existing UTF-8 sources.

If we want to _always_ enforce the BOM we'd have to also define the `fallback_encoding`:

```json
{
    "default_encoding": "UTF-8 with BOM",
    "fallback_encoding": "UTF-8 with BOM",
}
```

which will at least always complain when an encoding other than UTF-8 BOM is encountered ... but this might not be justified in a package settings file.

The goal is to ensure that new PB files will have a BOM, but also that legacy ASCII sources can be safely handled. So I think the current solution is good enough, especially since ASCII mode was dropped in PB 5.50 and is no longer in use — furthermore, what "ASCII" means in terms of encoding in modern OSs is anyone's guess.
