### ISSUE TITLE
Test files should be valid PureBasic source code

### ISSUE THREAD

**Issue by peterthomashorn** [peterthomashorn/purebasic-language-for-sublime-text#50]
Originally written by @tajmone as part of some contribution guideline proposals:

> Because we often need to cover invalid syntax elements which would lead to a compiler error (e.g. an invalid escape like `\Z` would raise a compiler error), or cover syntax quirks which are valid for the PBCompiler (e.g. a floating point number like `1.575e+1bananas` is perfectly valid PB code, just as decimals with leading zero like `0001` are) we should ensure that each test file is a valid PB source that can be compiled.
> 
> In the case of tests for invalid code which is expected to raise compiler errors, we should just annotate what compiler errors are expected — e.g. the `\Z` escape resulting in the compiler error:
> 
>     Invalid escape sequence in literal string: \Z
> 
> For a practical example of the above (except for the file naming convention), see the [Tests-Fail/syntax_test_escapes.pb](https://github.com/tajmone/purebasic-language-for-sublime-text/blob/fail-tests/Tests-Fail/syntax_test_escapes.pb) on my fork.
> 
> Since syntax tests can quickly grow in number and size, I think that annotating them is beneficial for both maintainers and contributors, especially if in the future the package might need a major revisiting because of a new PureBasic version having been released after the package wasn't updated for a long time (these things do happen, since life is unpredictable and it might as well be that both of use might end up not working with PB in the future, for various reasons).
> 
> Leaving behind well annotated tests and code can be a blessing for anyone taking on the project in the future, and also of great help for us if we end up not working on the package for a while — I often end up being spread thin across multiple projects, so my memory tends to fade away fast as I focus on what's right in front of me. Personally, I find annotated comments really useful when resuming work, they allow me to quickly get back on track knowing where I left things at.
> 
> Also worth keeping in mind, someone might use this repository as a reference to create a PureBasic syntax for another editor, in which case these comments will help adapting the tests and syntax definition to whatever system/format the target editor adopts. It's not unusual to come across a ST syntax based on a TextMate, Atom or VScode package.
> 
> Any annotations in the test file won't end up in the final package, so they are not a burden for the package, but can make a huge difference for contributors.
> 
> And, if my add, the list of PureBasic's language quirks is so long that it's hard to remember them all, and without comments they are not intuitive to grasp either. Example, try to compile the following code:
> 
>     FloatingApples.f  = 1.575e+1apples
>     FloatingBananas.f = 1.575e+1bananas
> 
>     If FloatingApples = FloatingBananas
>       Debug "They are identical!"
>     EndIf
> 
> it's perfectly valid and will pass the test — a reminder that documentation claims like PureBasic being [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) compliant need to be taken with a pinch of salt, for even if it is compliant in behavioural terms it surely isn't compliant when it comes to its notation. Since PB relies on `.f` and `.d` to distinguish between the different types of float numbers, the PBCompiler captures and ignores any trailing `[a-z]` characters. Of course, none of this is documented anywhere, it's part of those "PureBasic things" which need to be learned the hard way, via trial and error, and often discovered by accident.
> 
> That's an example of an edge case that needs to be well commented in the test files, otherwise anyone looking at the test will fail to grasp what's happening. And of course, being able to compile the actual test file is the final proof regarding the quirk.

**Comment by peterthomashorn** [comment]
As mentioned in #45 this could be even be automated with something simple like this shell script:

```zsh
#!/bin/zsh

set -e

for FILE in Tests/*(.)
do
    pbcompiler --check "$FILE"
done
```

The shell script is not portable enough, though. Originally this was only a proposal for the syntax tests anyway. I guess it is sufficient to just add it it to the `CONTRIBUTING.md` document.

**Comment by tajmone** [comment]
# Some PB Test Files Expected to Fail Compiling

> As mentioned in #45 this could be even be automated ...

Bear in mind that we'll also need to include tests catching `invalid` scopes, i.e. code examples that would lead to compiler failure — e.g. an invalid escape character inside an escapable string, which should be scoped as `invalid.[etc.]`, to warn the user that it will lead to a compiler error.

If you add to the build automation of testing all PB code by compiling, then you'll also need to ensure that there's either:

1. A file naming convention that allows to distinguish tests that are excepted to fail compiling (e.g. a trailing `_fail` before the `.pb` extension).
2. A dedicated folder for tests files that fail compiling.

The you could either skip the failing tests altogether, or expect an error exit code (although there is not much of a point in testing compiling failures).


# Issue with PB License

Another issue worth considering is that PureBasic is a commercial tool, and its EULA doesn't allow installing it on third party machines.

I actually brought up the issue with Fred regarding using PB for CI tests (see fantaisie-software/purebasic#3), but he hasn't yet come up with a solution, although he is interested in this. Ideally, he could make an hoc version of the compiler that only tests the source, without generating a compiled file, which he could then make freely available for testing purposes. Either that, or authorize CI usage, provided that all precautions are taken to ensure that the uploaded PB package can't be downloaded by third parties or used to compile online by people who don't have a PB license.

I'm afraid that until then, or lacking and explicit permission, there's no way to integrate the PBCompile in a third party CI service, but only on machines owned by PB licensee.

**Comment by peterthomashorn** [comment]
You are completely right. Thanks for the CI issue reference, I subscribed to it.
